# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arealocation',
            name='rests',
        ),
        migrations.AddField(
            model_name='arealocation',
            name='rests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_app.Rest'),
        ),
        migrations.RemoveField(
            model_name='arealocation',
            name='stations',
        ),
        migrations.AddField(
            model_name='arealocation',
            name='stations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_app.GasStation'),
        ),
        migrations.RemoveField(
            model_name='arealocation',
            name='stores',
        ),
        migrations.AddField(
            model_name='arealocation',
            name='stores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_app.Store'),
        ),
    ]
