# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_auto_20160323_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasstation',
            options={'ordering': ('station_name',)},
        ),
        migrations.AlterModelOptions(
            name='rest',
            options={'ordering': ('rest_name',)},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('store_name',)},
        ),
        migrations.AlterField(
            model_name='arealocation',
            name='rests',
            field=models.ManyToManyField(blank=True, to='map_app.Rest'),
        ),
        migrations.AlterField(
            model_name='arealocation',
            name='stations',
            field=models.ManyToManyField(blank=True, to='map_app.GasStation'),
        ),
        migrations.AlterField(
            model_name='arealocation',
            name='stores',
            field=models.ManyToManyField(blank=True, to='map_app.Store'),
        ),
    ]
